export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    source_type TEXT NOT NULL,
    content TEXT NOT NULL,
    word_count INTEGER NOT NULL,
    estimated_pages REAL,
    language TEXT DEFAULT 'en',
    structure_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT
  )`,
  'CREATE INDEX IF NOT EXISTS idx_documents_created_at ON documents(created_at)',
  'CREATE INDEX IF NOT EXISTS idx_documents_updated_at ON documents(updated_at)',
  'CREATE INDEX IF NOT EXISTS idx_documents_archived_at ON documents(archived_at)',
  `CREATE TABLE IF NOT EXISTS document_chapters (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id),
    title TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_document_chapters_document_order ON document_chapters(document_id, sort_order)',
  `CREATE TABLE IF NOT EXISTS document_pages (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id),
    chapter_id TEXT NOT NULL REFERENCES document_chapters(id),
    sort_order INTEGER NOT NULL,
    page_number INTEGER NOT NULL,
    source_page_number INTEGER,
    title TEXT,
    text TEXT NOT NULL,
    word_count INTEGER NOT NULL,
    review_status TEXT NOT NULL,
    ocr_confidence REAL,
    ocr_notes TEXT,
    uncertain_spans_json TEXT NOT NULL DEFAULT '[]',
    source_file_id TEXT,
    source_file_name TEXT,
    source_kind TEXT,
    source_local_path TEXT,
    source_sha256 TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_document_pages_document_order ON document_pages(document_id, sort_order)',
  'CREATE INDEX IF NOT EXISTS idx_document_pages_chapter_order ON document_pages(chapter_id, sort_order)',
  `CREATE TABLE IF NOT EXISTS source_files (
    id TEXT PRIMARY KEY,
    document_id TEXT REFERENCES documents(id),
    kind TEXT NOT NULL,
    display_name TEXT NOT NULL,
    local_path TEXT,
    sha256 TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ocr_jobs (
    id TEXT PRIMARY KEY,
    document_id TEXT REFERENCES documents(id),
    target_chapter_id TEXT REFERENCES document_chapters(id),
    status TEXT NOT NULL,
    model_id TEXT NOT NULL,
    input_file_count INTEGER NOT NULL,
    prompt_version TEXT NOT NULL,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT
  )`,
  'CREATE INDEX IF NOT EXISTS idx_ocr_jobs_status ON ocr_jobs(status)',
  'CREATE INDEX IF NOT EXISTS idx_ocr_jobs_created_at ON ocr_jobs(created_at)',
  `CREATE TABLE IF NOT EXISTS ocr_job_items (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES ocr_jobs(id),
    order_index INTEGER NOT NULL,
    source_file_name TEXT NOT NULL,
    source_file_type TEXT NOT NULL,
    source_file_size INTEGER NOT NULL,
    source_file_last_modified INTEGER NOT NULL,
    source_page_number INTEGER,
    title TEXT,
    status TEXT NOT NULL,
    ocr_text TEXT,
    pages_json TEXT NOT NULL DEFAULT '[]',
    warnings_json TEXT NOT NULL DEFAULT '[]',
    failure_reason TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_ocr_job_items_job_order ON ocr_job_items(job_id, order_index)',
  'CREATE INDEX IF NOT EXISTS idx_ocr_job_items_status ON ocr_job_items(status)',
  `CREATE TABLE IF NOT EXISTS ai_usage_line_items (
    id TEXT PRIMARY KEY,
    document_id TEXT REFERENCES documents(id),
    ocr_job_id TEXT REFERENCES ocr_jobs(id),
    ocr_item_id TEXT REFERENCES ocr_job_items(id),
    source_file_name TEXT,
    stage TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    failure_message TEXT,
    raw_provider_metadata_json TEXT,
    token_breakdown_json TEXT NOT NULL DEFAULT '{}',
    pricing_snapshot_json TEXT
  )`,
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_document_id ON ai_usage_line_items(document_id)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_ocr_job_id ON ai_usage_line_items(ocr_job_id)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_ocr_item_id ON ai_usage_line_items(ocr_item_id)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_stage ON ai_usage_line_items(stage)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_provider ON ai_usage_line_items(provider)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_model ON ai_usage_line_items(model)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_status ON ai_usage_line_items(status)',
  'CREATE INDEX IF NOT EXISTS idx_ai_usage_line_items_started_at ON ai_usage_line_items(started_at)',
  `CREATE TABLE IF NOT EXISTS reading_sessions (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id),
    scope_type TEXT DEFAULT 'document',
    scope_label TEXT,
    chapter_id TEXT,
    chapter_title TEXT,
    page_ids_json TEXT NOT NULL DEFAULT '[]',
    page_numbers_json TEXT NOT NULL DEFAULT '[]',
    source_page_numbers_json TEXT NOT NULL DEFAULT '[]',
    mode TEXT NOT NULL,
    target_wpm INTEGER NOT NULL,
    actual_wpm REAL NOT NULL,
    adjusted_wpm REAL,
    words_read INTEGER NOT NULL,
    duration_seconds INTEGER NOT NULL,
    start_position INTEGER NOT NULL,
    end_position INTEGER NOT NULL,
    pause_count INTEGER DEFAULT 0,
    regression_count INTEGER DEFAULT 0,
    comprehension_score REAL,
    self_rating INTEGER,
    notes TEXT DEFAULT '',
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_reading_sessions_document_id ON reading_sessions(document_id)',
  'CREATE INDEX IF NOT EXISTS idx_reading_sessions_started_at ON reading_sessions(started_at)',
  'CREATE INDEX IF NOT EXISTS idx_reading_sessions_mode ON reading_sessions(mode)',
  `CREATE TABLE IF NOT EXISTS quiz_attempts (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id),
    reading_session_id TEXT REFERENCES reading_sessions(id),
    kind TEXT NOT NULL,
    scope_type TEXT NOT NULL DEFAULT 'document',
    scope_label TEXT,
    chapter_id TEXT,
    chapter_title TEXT,
    page_ids_json TEXT NOT NULL DEFAULT '[]',
    page_numbers_json TEXT NOT NULL DEFAULT '[]',
    source_page_numbers_json TEXT NOT NULL DEFAULT '[]',
    start_word_index INTEGER NOT NULL,
    end_word_index INTEGER NOT NULL,
    word_count INTEGER NOT NULL,
    duration_seconds INTEGER NOT NULL,
    target_wpm INTEGER NOT NULL,
    raw_wpm REAL NOT NULL,
    adjusted_wpm REAL NOT NULL,
    comprehension_percent REAL NOT NULL,
    recommended_wpm INTEGER NOT NULL,
    explanation TEXT NOT NULL,
    question_results_json TEXT NOT NULL DEFAULT '[]',
    questions_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_quiz_attempts_document_id ON quiz_attempts(document_id)',
  'CREATE INDEX IF NOT EXISTS idx_quiz_attempts_reading_session_id ON quiz_attempts(reading_session_id)',
  'CREATE INDEX IF NOT EXISTS idx_quiz_attempts_kind ON quiz_attempts(kind)',
  'CREATE INDEX IF NOT EXISTS idx_quiz_attempts_created_at ON quiz_attempts(created_at)',
  `CREATE TABLE IF NOT EXISTS comprehension_checks (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES reading_sessions(id),
    question TEXT NOT NULL,
    answer_type TEXT NOT NULL,
    expected_answer TEXT,
    user_answer TEXT,
    score REAL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
]
